const LOAD_PRODUCTS_BEGIN='LOAD_PRODUCTS_BEGIN';
const LOAD_PRODUCTS_SUCCESS='LOAD_PRODUCTS_SUCCESS';
const LOAD_PRODUCTS_FAIL='LOAD_PRODUCTS_FAIL';
const OPEN_SIDEBAR='OPEN_SIDEBAR';
const CLOSE_SIDEBAR=' CLOSE_SIDEBAR';




export {LOAD_PRODUCTS_BEGIN,LOAD_PRODUCTS_SUCCESS,LOAD_PRODUCTS_FAIL,OPEN_SIDEBAR,CLOSE_SIDEBAR}