const LOAD_PRODUCTS_BEGIN='LOAD_PRODUCTS_BEGIN';
const LOAD_PRODUCTS_SUCCESS='LOAD_PRODUCTS_SUCCESS';
const LOAD_PRODUCTS_FAIL='LOAD_PRODUCTS_FAIL';
const LOAD_PRODUCT_BEGIN='LOAD_PRODUCT_BEGIN';
const LOAD_PRODUCT_SUCCESS='LOAD_PRODUCT_SUCCESS';
const LOAD_PRODUCT_FAIL='LOAD_PRODUCT_FAIL';
const OPEN_SIDEBAR='OPEN_SIDEBAR';
const CLOSE_SIDEBAR=' CLOSE_SIDEBAR';
const FILTER_PRODUCTS='FILTER_PRODUCTS';
const CHANGE_VIEW='CHANGE_VIEW';
const SORT_BY='SORT_BY';
const CLEAR_FILTERS='CLEAR_FILTERS';
const HANDLE_IMAGE='HANDLE_IMAGE';
const GET_ID='GET_ID';
const HANDLE_MAIN_COLOR='HANDLE_MAIN_COLOR';
const HANDLE_CART_ITEM='HANDLE_CART_ITEM';
const HANDLE_CART_ITEM_AMOUNT='HANDLE_CART_ITEM_AMOUNT';
const HANDLE_AMOUNT='HANDLE_AMOUNT';
const REMOVE_ITEM='REMOVE_ITEM';
const GET_ORDER_TOTAL='GET_ORDER_TOTAL';
const CLEAR_CART='CLEAR_CART';





export {LOAD_PRODUCTS_BEGIN,LOAD_PRODUCTS_SUCCESS,LOAD_PRODUCTS_FAIL,OPEN_SIDEBAR,CLOSE_SIDEBAR,FILTER_PRODUCTS,CHANGE_VIEW,SORT_BY,CLEAR_FILTERS,LOAD_PRODUCT_BEGIN,LOAD_PRODUCT_SUCCESS,LOAD_PRODUCT_FAIL,GET_ID,HANDLE_IMAGE,HANDLE_MAIN_COLOR,HANDLE_CART_ITEM,HANDLE_AMOUNT,HANDLE_CART_ITEM_AMOUNT,REMOVE_ITEM,GET_ORDER_TOTAL,CLEAR_CART}