const LOAD_PRODUCTS_BEGIN='LOAD_PRODUCTS_BEGIN';
const LOAD_PRODUCTS_SUCCESS='LOAD_PRODUCTS_SUCCESS';
const LOAD_PRODUCTS_FAIL='LOAD_PRODUCTS_FAIL';




export {LOAD_PRODUCTS_BEGIN,LOAD_PRODUCTS_SUCCESS,LOAD_PRODUCTS_FAIL}