const LOAD_DATA='LOAD_DATA';
const REMOVE_ITEM='REMOVE_ITEM';
const CLEAR_CART='CLEAR_CART';
const CHANGE_AMOUNT='CHANGE_AMOUNT';
const GET_TOTAL_AMOUNT='GET_TOTAL_AMOUNT';




export{LOAD_DATA,REMOVE_ITEM,CLEAR_CART,CHANGE_AMOUNT,GET_TOTAL_AMOUNT}